### ISSUE TITLE
Z80-MBC3 to assemble

### ISSUE THREAD

**Issue by hosamki** [eprive/Z80-MBC3#4]
I want to buy a Z80-MBC3 to assemble. What should I do?

**Comment by hosamki** [comment]
I live in Seoul, South Korea.

**Comment by eprive** [comment]
There is a webshop that is dedicated to the Z80-MBC3. You will find it here : https://eighties.company.site/

And you can choose the kit to be assembled, or a ready made and tested board.

You can use the email address ( eprive@gmx.com ) as mentioned under my account for future enquiries.

eprive

**Comment by hosamki** [comment]
I tried to order on the site you told me, but it cannot be delivered to South Korea. 
Why?

**Comment by hosamki** [comment]
There is not South Korea (or Republic of Korea) in Country of Shipping & Delivery.

**Comment by hosamki** [comment]
I sent you a email.

**Comment by hosamki** [comment]
I checked that "Republic of Korea" was added to the list of countries. 
So I just ordered and paid for two Z80-MBC3. 
I look forward to receiving it as soon as possible.
