### ISSUE TITLE
Flashing the 4809

### ISSUE THREAD

**Issue by JanChrisKlein** [eprive/Z80-MBC3#6]
Hi,

I wanted to flash a new AT4809 with the latest firmware and can't seem to connect.
Is there any preparation necessary for doing this? Can You use a factory new
chip or does it have to contain a specific bootloader? Any (hidden) jumpers?

The original AT4809 that came with the kit works fine. Only, I don't want to destroy
that.

Or is my (pricey) New-Chip-EBay buy crappy?

Christoph

**Comment by eprive** [comment]
Programming a blank AT4809-PF requires a UPDI programmer to load the custom bootloader for the Z80-MBC3. This has been done with the controllers that come with the kit. So you can only use the ATmega4809 that is contained in the kit.

The boatloader contains the code that works with avr-dude to enable firmware updates over the serial port.
I'd like to know why you want to replace the ATmega4809 with another ....

**Comment by JanChrisKlein** [comment]
Never done changing the firmware before. I didn't want to risk wasting my functioning IOS...
Would flashing the 4809 with Your IOS.HEX file mean, that furthermore updates with avr-dude were possible?

Christoph

**Comment by eprive** [comment]
Yes, you can load any update ( or revert to an older version ) using avr-dude and the procedure that is documented.

As long as the you do not fully erase the part, or modify the bootloader.
