### ISSUE TITLE
atmega4809 programming

### ISSUE THREAD

**Issue by mciucci65** [eprive/Z80-MBC3#8]
thanks again for uploading gerber and  etc.
I have successfully programmed the atmega4809 with Arduino Uno and Jtag2updi. 
I programmed the chip 4809 with flash.bat and result is successfully programmed.
The Program compare.bat tells me that flash compared with ios hex file is ok  but when I start with a CPU Z84C0020PEC, working on MBC2,  the Halt LED turn on and nothing happens and the CPU warms up. If I start without cpu I don't see anything while with the MBC2 at least I see the boot of the mega32a chip.
I checked also with oscilloscope the cpu clock and it is 5mhz.
There is something wrong that I am doing to program the 4809 chip needing a bootloader and specific value for fuses ?

**Comment by eprive** [comment]
Your question raises several other questions, MBC2 or MBC3 ? Only ATmega4809 chips that are contained in the (complete) Z80-MBC3 kit or assembled boards will function. Other (blank) ATmega4809-PF's cannot be used.
And they are unsuitable for the older Z80-MBC2. As are derivatives or attempts to clone the Z80-MBC3.
